id: ICC43AC45
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:16:14+00:00'
last_modified: '2022-06-08T02:25:26.173537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3MS838
  title: བརྡ་སྤྲོད་དཀའ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3814':
      image_group_id: I3MS840
      title: ''
      total_pages: 231
      order: 1
      base_file: 3814.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
