id: P004628
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3MS838
  title: བརྡ་སྤྲོད་དཀའ་འགྲེལ།
  author: ''
  volumes:
    3c26ac0af66343a6aa157d88dbd6148e:
      image_group_id: I3MS840
      title: ''
      volume_number: 1
      total_pages: 231
      base_file: v001.txt
